# Generated by Django 5.1.6 on 2025-05-01 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('uphn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('uname', models.CharField(max_length=20)),
                ('uemail', models.EmailField(max_length=50, unique=True)),
                ('uadd', models.CharField(max_length=50)),
                ('upwd', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('dphn', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('dname', models.CharField(max_length=20)),
                ('demail', models.EmailField(max_length=30, unique=True)),
                ('dadd', models.CharField(max_length=50)),
                ('dpwd', models.CharField(max_length=128)),
            ],
        ),
    ]
